import CryptoKit
import Foundation
import UniformTypeIdentifiers

/// The clipboard history's pure decisions: search, order, trimming, pins,
/// titles, what to ignore and when two copies are "the same". Nothing here
/// touches the pasteboard or the disk, so `--check` can pin all of it down.
enum ClipboardLogic {
    /// Search only looks this far into an entry: a pasted log file shouldn't
    /// make every keystroke in the popup crawl.
    static let searchLimit = 5000
    /// A list title never runs longer than this.
    static let titleLimit = 1000

    // MARK: - Pasteboard type names

    static let plainTextType = "public.utf8-plain-text"
    static let legacyStringType = "NSStringPboardType"
    static let fileURLType = "public.file-url"
    static let sourceType = "org.nspasteboard.source"

    /// Formatting that "Save rich text" off throws away.
    static let richTextTypes: Set<String> = [
        "public.rtf", "public.rtfd", "com.apple.flat-rtfd", "public.html", "com.apple.webarchive",
        "Apple HTML pasteboard type", "NeXT Rich Text Format v1.0 pasteboard type", "NeXT RTFD pasteboard type",
    ]

    /// Marks a copy as "don't keep me" — password managers and apps that put
    /// throwaway data on the pasteboard use these (nspasteboard.org).
    static let alwaysIgnoredTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "de.petermaurer.TransientPasteboardType",
        "Pasteboard generator type",
        "net.antelle.keeweb",
    ]

    /// Types that change between two copies of the same thing (the page a
    /// browser copied from, WebKit's private blob), so they're left out when
    /// deciding whether a copy is a repeat.
    static let volatileTypes: Set<String> = [
        "com.ivy.tempo.clip", sourceType, "org.chromium.source-url",
        "com.apple.WebKit.custom-pasteboard-data", "org.chromium.web-custom-data",
    ]

    static func isImageType(_ type: String) -> Bool {
        guard let ut = UTType(type) else { return false }
        return ut.conforms(to: .image)
    }

    static func isRichTextType(_ type: String) -> Bool { richTextTypes.contains(type) }

    static func isPlainTextType(_ type: String) -> Bool { type == plainTextType || type == legacyStringType }

    // MARK: - Search

    /// Whether an entry's title matches what's typed in the popup. An empty
    /// query matches everything; an invalid regex searches as plain text.
    static func matches(_ title: String, query: String, mode: ClipSearchMode) -> Bool {
        guard !query.isEmpty else { return true }
        let text = searchable(title)
        switch mode {
        case .exact:
            return exactMatch(text, query: query)
        case .fuzzy:
            return fuzzyScore(text, query: query) != nil
        case .regex:
            guard let regex = regex(query) else { return exactMatch(text, query: query) }
            return regexMatch(text, regex: regex)
        }
    }

    /// The entries that match, in the order given — except fuzzy search,
    /// which puts the closest matches first. An entry matches on its title or
    /// on the text read out of its image (`ocrText`); fuzzy search scores the
    /// better of the two. Pinned entries stay ahead of the rest either way
    /// when `pinsOnTop` is on.
    static func filter(_ items: [ClipItem], query: String, mode: ClipSearchMode, pinsOnTop: Bool = true) -> [ClipItem] {
        guard !query.isEmpty else { return items }
        switch mode {
        case .exact:
            return items.filter { searchTexts($0).contains { exactMatch($0, query: query) } }
        case .regex:
            guard let regex = regex(query) else {
                return items.filter { searchTexts($0).contains { exactMatch($0, query: query) } }
            }
            return items.filter { searchTexts($0).contains { regexMatch($0, regex: regex) } }
        case .fuzzy:
            let folded = fold(query)
            let scored = items.enumerated().compactMap { index, item -> (Int, Int, ClipItem)? in
                let scores = searchTexts(item).compactMap { foldedFuzzyScore(fold($0), query: folded) }
                guard let score = scores.max() else { return nil }
                return (score, index, item)
            }
            return scored.sorted { a, b in
                if pinsOnTop, a.2.isPinned != b.2.isPinned { return a.2.isPinned }
                if a.0 != b.0 { return a.0 > b.0 }
                return a.1 < b.1  // equal scores keep the history's order
            }.map(\.2)
        }
    }

    /// What search looks at for an entry: its title, plus the text read out
    /// of its image when there is some. Each is cut at `searchLimit`.
    static func searchTexts(_ item: ClipItem) -> [String] {
        var texts = [searchable(item.title)]
        if let ocr = item.ocrText, !ocr.isEmpty { texts.append(searchable(ocr)) }
        return texts
    }

    /// How well `query` matches `text` as a subsequence (letters in order,
    /// gaps allowed); nil when it doesn't. Runs of consecutive letters and
    /// letters starting a word score higher, so "gc" ranks "git checkout"
    /// above "logic".
    static func fuzzyScore(_ text: String, query: String) -> Int? {
        foldedFuzzyScore(fold(text), query: fold(query))
    }

    private static func foldedFuzzyScore(_ text: String, query: String) -> Int? {
        let q = Array(query.unicodeScalars).filter { !CharacterSet.whitespaces.contains($0) }
        guard !q.isEmpty else { return 0 }
        let t = Array(text.unicodeScalars)
        var score = 0
        var qi = 0
        var previousMatch = -2
        var firstMatch: Int?
        for (ti, scalar) in t.enumerated() where qi < q.count {
            guard scalar == q[qi] else { continue }
            score += 1
            if ti == previousMatch + 1 { score += 5 }
            let atWordStart = ti == 0 || !CharacterSet.alphanumerics.contains(t[ti - 1])
            if atWordStart { score += 3 }
            if firstMatch == nil { firstMatch = ti }
            previousMatch = ti
            qi += 1
        }
        guard qi == q.count else { return nil }
        // A match that starts late is a little worse than one near the front.
        return score - min(firstMatch ?? 0, 10)
    }

    private static func searchable(_ title: String) -> String {
        title.count > searchLimit ? String(title.prefix(searchLimit)) : title
    }

    private static func fold(_ s: String) -> String {
        s.folding(options: [.caseInsensitive, .diacriticInsensitive], locale: nil)
    }

    private static func exactMatch(_ text: String, query: String) -> Bool {
        text.range(of: query, options: [.caseInsensitive, .diacriticInsensitive]) != nil
    }

    private static func regex(_ pattern: String) -> NSRegularExpression? {
        try? NSRegularExpression(pattern: pattern, options: [.caseInsensitive])
    }

    private static func regexMatch(_ text: String, regex: NSRegularExpression) -> Bool {
        regex.firstMatch(in: text, range: NSRange(text.startIndex..., in: text)) != nil
    }

    // MARK: - Text in images (OCR)

    /// Recognised text is kept up to this many characters.
    static let ocrLimit = 5000

    /// Joins the lines Vision read into an entry's `ocrText`: each line
    /// trimmed, empty ones dropped, one per line, cut at `ocrLimit`. An image
    /// with no text gives "" — read, nothing found, never tried again.
    static func ocrText(lines: [String]) -> String {
        let text = lines.map { $0.trimmingCharacters(in: .whitespacesAndNewlines) }
            .filter { !$0.isEmpty }
            .joined(separator: "\n")
        return text.count > ocrLimit ? String(text.prefix(ocrLimit)) : text
    }

    /// Image entries whose text hasn't been read yet, most recently copied
    /// first (the ones most likely to be searched for).
    static func needingOCR(_ items: [ClipItem]) -> [UUID] {
        items.enumerated()
            .filter { $0.element.kind == .image && $0.element.ocrText == nil }
            .sorted { a, b in
                if a.element.lastCopied != b.element.lastCopied { return a.element.lastCopied > b.element.lastCopied }
                return a.offset < b.offset
            }
            .map(\.element.id)
    }

    // MARK: - Order and size

    /// The history in display order. Pinned entries lead when `pinsOnTop`;
    /// within each group the chosen order applies, newest first on ties.
    static func sorted(_ items: [ClipItem], by sort: ClipSort, pinsOnTop: Bool) -> [ClipItem] {
        items.enumerated().sorted { a, b in
            let x = a.element, y = b.element
            if pinsOnTop, x.isPinned != y.isPinned { return x.isPinned }
            switch sort {
            case .lastCopied:
                if x.lastCopied != y.lastCopied { return x.lastCopied > y.lastCopied }
            case .firstCopied:
                if x.firstCopied != y.firstCopied { return x.firstCopied > y.firstCopied }
            case .copyCount:
                if x.copies != y.copies { return x.copies > y.copies }
                if x.lastCopied != y.lastCopied { return x.lastCopied > y.lastCopied }
            }
            return a.offset < b.offset
        }.map(\.element)
    }

    /// Splits the history at the size limit: pinned entries always stay, and
    /// of the rest the most recently copied `limit` stay. `kept` keeps the
    /// input order.
    static func trimmed(_ items: [ClipItem], limit: Int) -> (kept: [ClipItem], dropped: [ClipItem]) {
        let unpinned = items.filter { !$0.isPinned }
        guard unpinned.count > max(limit, 0) else { return (items, []) }
        let keep = Set(unpinned.sorted { $0.lastCopied > $1.lastCopied }.prefix(max(limit, 0)).map(\.id))
        var kept: [ClipItem] = [], dropped: [ClipItem] = []
        for item in items {
            if item.isPinned || keep.contains(item.id) { kept.append(item) } else { dropped.append(item) }
        }
        return (kept, dropped)
    }

    // MARK: - Pins

    /// Letters a pin can take, in the order they're handed out. Left out:
    /// a, c, q, v, w, x, z (⌘A, ⌘C, ⌘Q, ⌘V, ⌘W, ⌘X and ⌘Z keep their usual
    /// meaning in the popup's search field) and d, p — the popup's own delete
    /// and pin keys.
    static let pinLetters: [String] = "befghijklmnorstuy".map(String.init)

    /// The first letter not already pinned, or nil when every one is taken.
    static func nextPin(used: Set<String>) -> String? {
        pinLetters.first { !used.contains($0) }
    }

    // MARK: - Titles and kinds

    /// The list line for copied text: trimmed, every run of spaces, tabs and
    /// newlines collapsed to one space, control characters removed, and cut
    /// at `titleLimit` characters.
    static func title(forText text: String) -> String {
        var out = String.UnicodeScalarView()
        var count = 0
        var pendingSpace = false
        for scalar in text.unicodeScalars {
            if CharacterSet.whitespacesAndNewlines.contains(scalar) {
                pendingSpace = count > 0
                continue
            }
            // Only true control codes go; format characters (the joiners
            // inside emoji) must stay.
            if scalar.properties.generalCategory == .control { continue }
            if pendingSpace {
                out.append(" ")
                count += 1
                pendingSpace = false
                if count >= titleLimit { break }
            }
            out.append(scalar)
            count += 1
            if count >= titleLimit { break }
        }
        let result = String(out)
        return result.count > titleLimit ? String(result.prefix(titleLimit)) : result
    }

    /// `.color` for a hex colour (#RGB, #RRGGBB, #RRGGBBAA), `.link` for a
    /// single http(s) address, `.text` for anything else.
    static func kind(forText text: String) -> ClipKind {
        let s = text.trimmingCharacters(in: .whitespacesAndNewlines)
        if isHexColor(s) { return .color }
        if isWebLink(s) { return .link }
        return .text
    }

    static func isHexColor(_ s: String) -> Bool {
        guard s.hasPrefix("#") else { return false }
        let hex = s.dropFirst()
        guard [3, 6, 8].contains(hex.count) else { return false }
        return hex.allSatisfy(\.isHexDigit)
    }

    private static func isWebLink(_ s: String) -> Bool {
        guard !s.isEmpty, s.count < 4096, s.rangeOfCharacter(from: .whitespacesAndNewlines) == nil,
            let url = URL(string: s), let scheme = url.scheme?.lowercased(),
            scheme == "http" || scheme == "https", let host = url.host, !host.isEmpty
        else { return false }
        return true
    }

    // MARK: - What to keep

    /// Whether a copy carries a "don't record me" type (a password manager's
    /// marker, a transient helper copy) or one the user listed.
    static func shouldIgnore(types: [String], ignoredTypes: [String]) -> Bool {
        let user = Set(ignoredTypes.map { $0.trimmingCharacters(in: .whitespaces) }.filter { !$0.isEmpty })
        return types.contains { alwaysIgnoredTypes.contains($0) || user.contains($0) }
    }

    /// The types worth storing: drops the system's anonymous `dyn.*` types,
    /// Office's OLE and link-source blobs, bookmark types and Tempo's own
    /// marker. Order is kept.
    static func storableTypes(_ types: [String]) -> [String] {
        // The UTF-16 text twin is the same words again; the pasteboard makes
        // it from the UTF-8 text on demand, so storing it only doubles size.
        let hasUTF8 = types.contains("public.utf8-plain-text")
        return types.filter { type in
            if hasUTF8 && type == "public.utf16-external-plain-text" { return false }
            if type.hasPrefix("dyn.") { return false }
            if type.hasPrefix("com.microsoft.ole.source") { return false }
            if type.hasPrefix("com.microsoft.Link-Source") { return false }
            if type.hasPrefix("com.microsoft.ObjectLink") { return false }
            if type.lowercased().contains("bookmark") { return false }
            if type == "com.ivy.tempo.clip" { return false }
            return true
        }
    }

    /// Whether copied text matches one of the user's "never record" regexes.
    /// Invalid or empty patterns are ignored.
    static func matchesIgnoredPattern(_ text: String, patterns: [String]) -> Bool {
        guard !text.isEmpty else { return false }
        let range = NSRange(text.startIndex..., in: text)
        for pattern in patterns where !pattern.isEmpty {
            guard let regex = try? NSRegularExpression(pattern: pattern) else { continue }
            if regex.firstMatch(in: text, range: range) != nil { return true }
        }
        return false
    }

    // MARK: - Identity

    /// What makes two copies "the same" for the history: a hash of the main
    /// content — the file list if there is one, else the plain text, else
    /// the image, else the first stored type. Files come before text because
    /// Finder's text is just the file name: two "report.pdf" from different
    /// folders are different copies. Formatting and volatile types (source
    /// page, WebKit blobs) don't count, so copying the same sentence twice
    /// bumps one entry instead of adding a second.
    static func fingerprint(_ pairs: [(type: String, data: Data)]) -> String {
        let stable = pairs.filter { !volatileTypes.contains($0.type) }
        let files = stable.filter { $0.type == fileURLType }
        if !files.isEmpty { return digest("files", files.map(\.data)) }
        if let text = stable.first(where: { $0.type == plainTextType }) ?? stable.first(where: { $0.type == legacyStringType }) {
            return digest("text", [text.data])
        }
        if let image = stable.first(where: { isImageType($0.type) }) {
            return digest("image", [image.data])
        }
        if let first = stable.first { return digest(first.type, [first.data]) }
        return digest("empty", [])
    }

    private static func digest(_ label: String, _ parts: [Data]) -> String {
        var hasher = SHA256()
        hasher.update(data: Data(label.utf8))
        for part in parts {
            var length = UInt64(part.count).littleEndian
            hasher.update(data: Data(bytes: &length, count: 8))
            hasher.update(data: part)
        }
        return label + ":" + hasher.finalize().map { String(format: "%02x", $0) }.joined()
    }
}
